/* tslint:disable */
/* eslint-disable */
/**
 * server
 * server
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    PingResponse,
    PingResponseFromJSON,
    PingResponseToJSON,
} from '../models';

/**
 * 
 */
export class PingControllerApi extends runtime.BaseAPI {

    /**
     */
    async pingControllerPingRaw(): Promise<runtime.ApiResponse<PingResponse>> {
        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/ping`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => PingResponseFromJSON(jsonValue));
    }

    /**
     */
    async pingControllerPing(): Promise<PingResponse> {
        const response = await this.pingControllerPingRaw();
        return await response.value();
    }

}
