/* tslint:disable */
/* eslint-disable */
/**
 * server
 * server
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LoginCredentials
 */
export interface LoginCredentials {
    /**
     * 
     * @type {string}
     * @memberof LoginCredentials
     */
    login: string;
    /**
     * 
     * @type {string}
     * @memberof LoginCredentials
     */
    password: string;
}

export function LoginCredentialsFromJSON(json: any): LoginCredentials {
    return LoginCredentialsFromJSONTyped(json, false);
}

export function LoginCredentialsFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginCredentials {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'login': json['login'],
        'password': json['password'],
    };
}

export function LoginCredentialsToJSON(value?: LoginCredentials | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'login': value.login,
        'password': value.password,
    };
}


