/* tslint:disable */
/* eslint-disable */
/**
 * server
 * server
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * (tsType: Omit<Restaurant, 'id'>, schemaOptions: { title: 'NewRestaurant', exclude: [ 'id' ] })
 * @export
 * @interface NewRestaurant
 */
export interface NewRestaurant {
    /**
     * 
     * @type {string}
     * @memberof NewRestaurant
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof NewRestaurant
     */
    ownerId?: string;
}

export function NewRestaurantFromJSON(json: any): NewRestaurant {
    return NewRestaurantFromJSONTyped(json, false);
}

export function NewRestaurantFromJSONTyped(json: any, ignoreDiscriminator: boolean): NewRestaurant {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'ownerId': !exists(json, 'ownerId') ? undefined : json['ownerId'],
    };
}

export function NewRestaurantToJSON(value?: NewRestaurant | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'ownerId': value.ownerId,
    };
}


