/* tslint:disable */
/* eslint-disable */
/**
 * server
 * server
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * (tsType: NewUserRequest, schemaOptions: { title: 'NewUser' })
 * @export
 * @interface NewUser
 */
export interface NewUser {
    /**
     * 
     * @type {string}
     * @memberof NewUser
     */
    login: string;
    /**
     * 
     * @type {string}
     * @memberof NewUser
     */
    password: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof NewUser
     */
    roles?: Array<NewUserRolesEnum>;
}

export function NewUserFromJSON(json: any): NewUser {
    return NewUserFromJSONTyped(json, false);
}

export function NewUserFromJSONTyped(json: any, ignoreDiscriminator: boolean): NewUser {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'login': json['login'],
        'password': json['password'],
        'roles': !exists(json, 'roles') ? undefined : json['roles'],
    };
}

export function NewUserToJSON(value?: NewUser | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'login': value.login,
        'password': value.password,
        'roles': value.roles,
    };
}

/**
* @export
* @enum {string}
*/
export enum NewUserRolesEnum {
    User = 'user',
    Business = 'business',
    Admin = 'admin'
}


