/* tslint:disable */
/* eslint-disable */
/**
 * server
 * server
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NewUserRequest
 */
export interface NewUserRequest {
    /**
     * 
     * @type {string}
     * @memberof NewUserRequest
     */
    login: string;
    /**
     * 
     * @type {string}
     * @memberof NewUserRequest
     */
    password: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof NewUserRequest
     */
    roles?: Array<NewUserRequestRolesEnum>;
}

export function NewUserRequestFromJSON(json: any): NewUserRequest {
    return NewUserRequestFromJSONTyped(json, false);
}

export function NewUserRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): NewUserRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'login': json['login'],
        'password': json['password'],
        'roles': !exists(json, 'roles') ? undefined : json['roles'],
    };
}

export function NewUserRequestToJSON(value?: NewUserRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'login': value.login,
        'password': value.password,
        'roles': value.roles,
    };
}

/**
* @export
* @enum {string}
*/
export enum NewUserRequestRolesEnum {
    User = 'user',
    Business = 'business',
    Admin = 'admin'
}


