/* tslint:disable */
/* eslint-disable */
/**
 * server
 * server
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    RestaurantScopeFilter,
    RestaurantScopeFilterFromJSON,
    RestaurantScopeFilterFromJSONTyped,
    RestaurantScopeFilterToJSON,
} from './index';

/**
 *
 * @export
 * @interface RestaurantIncludeFilterItems
 */
export interface RestaurantIncludeFilterItems {
    /**
     *
     * @type {string}
     * @memberof RestaurantIncludeFilterItems
     */
    relation?: string;
    /**
     *
     * @type {RestaurantScopeFilter}
     * @memberof RestaurantIncludeFilterItems
     */
    scope?: RestaurantScopeFilter;
}

export function RestaurantIncludeFilterItemsFromJSON(json: any): RestaurantIncludeFilterItems {
    return RestaurantIncludeFilterItemsFromJSONTyped(json, false);
}

export function RestaurantIncludeFilterItemsFromJSONTyped(json: any, ignoreDiscriminator: boolean): RestaurantIncludeFilterItems {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'relation': !exists(json, 'relation') ? undefined : json['relation'],
        'scope': !exists(json, 'scope') ? undefined : RestaurantScopeFilterFromJSON(json['scope']),
    };
}

export function RestaurantIncludeFilterItemsToJSON(value?: RestaurantIncludeFilterItems | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'relation': value.relation,
        'scope': RestaurantScopeFilterToJSON(value.scope),
    };
}


