/* tslint:disable */
/* eslint-disable */
/**
 * server
 * server
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface RestaurantFields
 */
export type RestaurantFields = {
    /**
     *
     * @type {boolean}
     * @memberof RestaurantFields
     */
    id?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof RestaurantFields
     */
    name?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof RestaurantFields
     */
    ownerId?: boolean;
}

export function RestaurantFieldsFromJSON(json: any): RestaurantFields {
    return RestaurantFieldsFromJSONTyped(json, false);
}

export function RestaurantFieldsFromJSONTyped(json: any, ignoreDiscriminator: boolean): RestaurantFields {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'ownerId': !exists(json, 'ownerId') ? undefined : json['ownerId'],
    };
}

export function RestaurantFieldsToJSON(value?: RestaurantFields | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'id': value.id,
        'name': value.name,
        'ownerId': value.ownerId,
    };
}


