/* tslint:disable */
/* eslint-disable */
/**
 * server
 * server
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * (tsType: Partial<Restaurant>, schemaOptions: { partial: true })
 * @export
 * @interface RestaurantPartial
 */
export interface RestaurantPartial {
    /**
     * 
     * @type {string}
     * @memberof RestaurantPartial
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof RestaurantPartial
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof RestaurantPartial
     */
    ownerId?: string;
}

export function RestaurantPartialFromJSON(json: any): RestaurantPartial {
    return RestaurantPartialFromJSONTyped(json, false);
}

export function RestaurantPartialFromJSONTyped(json: any, ignoreDiscriminator: boolean): RestaurantPartial {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'ownerId': !exists(json, 'ownerId') ? undefined : json['ownerId'],
    };
}

export function RestaurantPartialToJSON(value?: RestaurantPartial | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'ownerId': value.ownerId,
    };
}


