/* tslint:disable */
/* eslint-disable */
/**
 * server
 * server
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface ReviewFields
 */
export type ReviewFields = {
    /**
     *
     * @type {boolean}
     * @memberof ReviewFields
     */
    id?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof ReviewFields
     */
    rating?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof ReviewFields
     */
    comment?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof ReviewFields
     */
    date?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof ReviewFields
     */
    restaurantId?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof ReviewFields
     */
    authorId?: boolean;
}

export function ReviewFieldsFromJSON(json: any): ReviewFields {
    return ReviewFieldsFromJSONTyped(json, false);
}

export function ReviewFieldsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReviewFields {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'id': !exists(json, 'id') ? undefined : json['id'],
        'rating': !exists(json, 'rating') ? undefined : json['rating'],
        'comment': !exists(json, 'comment') ? undefined : json['comment'],
        'date': !exists(json, 'date') ? undefined : json['date'],
        'restaurantId': !exists(json, 'restaurantId') ? undefined : json['restaurantId'],
        'authorId': !exists(json, 'authorId') ? undefined : json['authorId'],
    };
}

export function ReviewFieldsToJSON(value?: ReviewFields | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'id': value.id,
        'rating': value.rating,
        'comment': value.comment,
        'date': value.date,
        'restaurantId': value.restaurantId,
        'authorId': value.authorId,
    };
}


