/* tslint:disable */
/* eslint-disable */
/**
 * server
 * server
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReviewResponse
 */
export interface ReviewResponse {
    /**
     * 
     * @type {string}
     * @memberof ReviewResponse
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ReviewResponse
     */
    comment: string;
    /**
     * 
     * @type {string}
     * @memberof ReviewResponse
     */
    reviewId?: string;
}

export function ReviewResponseFromJSON(json: any): ReviewResponse {
    return ReviewResponseFromJSONTyped(json, false);
}

export function ReviewResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReviewResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'comment': json['comment'],
        'reviewId': !exists(json, 'reviewId') ? undefined : json['reviewId'],
    };
}

export function ReviewResponseToJSON(value?: ReviewResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'comment': value.comment,
        'reviewId': value.reviewId,
    };
}


