/* tslint:disable */
/* eslint-disable */
/**
 * server
 * server
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ReviewScopeFilter,
    ReviewScopeFilterFromJSON,
    ReviewScopeFilterFromJSONTyped,
    ReviewScopeFilterToJSON,
} from './index';

/**
 *
 * @export
 * @interface ReviewIncludeFilterItems
 */
export type ReviewIncludeFilterItems = {
    /**
     *
     * @type {string}
     * @memberof ReviewIncludeFilterItems
     */
    relation?: string;
    /**
     *
     * @type {ReviewScopeFilter}
     * @memberof ReviewIncludeFilterItems
     */
    scope?: ReviewScopeFilter;
}

export function ReviewIncludeFilterItemsFromJSON(json: any): ReviewIncludeFilterItems {
    return ReviewIncludeFilterItemsFromJSONTyped(json, false);
}

export function ReviewIncludeFilterItemsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReviewIncludeFilterItems {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'relation': !exists(json, 'relation') ? undefined : json['relation'],
        'scope': !exists(json, 'scope') ? undefined : ReviewScopeFilterFromJSON(json['scope']),
    };
}

export function ReviewIncludeFilterItemsToJSON(value?: ReviewIncludeFilterItems | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'relation': value.relation,
        'scope': ReviewScopeFilterToJSON(value.scope),
    };
}


