/* tslint:disable */
/* eslint-disable */
/**
 * server
 * server
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * (tsType: ReviewResponseWithRelations, schemaOptions: { includeRelations: true })
 * @export
 * @interface ReviewResponseWithRelations
 */
export interface ReviewResponseWithRelations {
    /**
     * 
     * @type {string}
     * @memberof ReviewResponseWithRelations
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ReviewResponseWithRelations
     */
    comment: string;
    /**
     * 
     * @type {string}
     * @memberof ReviewResponseWithRelations
     */
    reviewId?: string;
}

export function ReviewResponseWithRelationsFromJSON(json: any): ReviewResponseWithRelations {
    return ReviewResponseWithRelationsFromJSONTyped(json, false);
}

export function ReviewResponseWithRelationsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReviewResponseWithRelations {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'comment': json['comment'],
        'reviewId': !exists(json, 'reviewId') ? undefined : json['reviewId'],
    };
}

export function ReviewResponseWithRelationsToJSON(value?: ReviewResponseWithRelations | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'comment': value.comment,
        'reviewId': value.reviewId,
    };
}


