/* tslint:disable */
/* eslint-disable */
/**
 * server
 * server
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Review
 */
export interface Review {
    /**
     * 
     * @type {string}
     * @memberof Review
     */
    id?: string;
    /**
     * 
     * @type {number}
     * @memberof Review
     */
    rating: number;
    /**
     * 
     * @type {string}
     * @memberof Review
     */
    comment: string;
    /**
     * 
     * @type {Date}
     * @memberof Review
     */
    date: Date;
    /**
     * 
     * @type {string}
     * @memberof Review
     */
    restaurantId?: string;
    /**
     * 
     * @type {string}
     * @memberof Review
     */
    authorId?: string;
}

export function ReviewFromJSON(json: any): Review {
    return ReviewFromJSONTyped(json, false);
}

export function ReviewFromJSONTyped(json: any, ignoreDiscriminator: boolean): Review {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'rating': json['rating'],
        'comment': json['comment'],
        'date': (new Date(json['date'])),
        'restaurantId': !exists(json, 'restaurantId') ? undefined : json['restaurantId'],
        'authorId': !exists(json, 'authorId') ? undefined : json['authorId'],
    };
}

export function ReviewToJSON(value?: Review | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'rating': value.rating,
        'comment': value.comment,
        'date': (value.date.toISOString()),
        'restaurantId': value.restaurantId,
        'authorId': value.authorId,
    };
}


