/* tslint:disable */
/* eslint-disable */
/**
 * server
 * server
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface UserFields
 */
export type UserFields = {
    /**
     *
     * @type {boolean}
     * @memberof UserFields
     */
    id?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof UserFields
     */
    name?: boolean;
    /**
     *
     * @type {boolean}
     * @memberof UserFields
     */
    roles?: boolean;
}

export function UserFieldsFromJSON(json: any): UserFields {
    return UserFieldsFromJSONTyped(json, false);
}

export function UserFieldsFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserFields {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'roles': !exists(json, 'roles') ? undefined : json['roles'],
    };
}

export function UserFieldsToJSON(value?: UserFields | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'id': value.id,
        'name': value.name,
        'roles': value.roles,
    };
}


