/* tslint:disable */
/* eslint-disable */
/**
 * server
 * server
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    UserScopeFilter,
    UserScopeFilterFromJSON,
    UserScopeFilterFromJSONTyped,
    UserScopeFilterToJSON,
} from './';

/**
 *
 * @export
 * @interface UserIncludeFilterItems
 */
export type UserIncludeFilterItems = {
    /**
     *
     * @type {string}
     * @memberof UserIncludeFilterItems
     */
    relation?: string;
    /**
     *
     * @type {UserScopeFilter}
     * @memberof UserIncludeFilterItems
     */
    scope?: UserScopeFilter;
}

export function UserIncludeFilterItemsFromJSON(json: any): UserIncludeFilterItems {
    return UserIncludeFilterItemsFromJSONTyped(json, false);
}

export function UserIncludeFilterItemsFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserIncludeFilterItems {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {

        'relation': !exists(json, 'relation') ? undefined : json['relation'],
        'scope': !exists(json, 'scope') ? undefined : UserScopeFilterFromJSON(json['scope']),
    };
}

export function UserIncludeFilterItemsToJSON(value?: UserIncludeFilterItems | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {

        'relation': value.relation,
        'scope': UserScopeFilterToJSON(value.scope),
    };
}


